---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

“This is a line from RStudio”


Experiences:

12.1: Some people were not connected to git on their RStudio, so they had to connect their RStudio before they could continue.


12.2: We just used the repository made for us in the lab.

1. Took a while to understand commit and pulling changes

12.3 Clone the test GitHub repository to your computer via RStudio

1. We had a relative smooth time in cloning the GitHub Repository
2. The Github was confusing at first but once we get the hang of it, everything went pretty smooth


12.4 Make local changes, save, commit
1. We struggled to commit the changes at first as we failed to staged our changes before committing

12.5: We could push relatively easily but we just needed an acess code to verify changes.

12.6: No problems encountered here we each saw when there was a new line in RStudio
